apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clinic-booking-api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.image.ports.name }}
  selector:
    {{- include "clinic-booking-api.selectorLabels" . | nindent 4}}
